### ISSUE TITLE
Repurpose thick lines between posts

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#44] opened 2012-11-12 18:29 UTC
In all views, there is a heavier line between every other post. What is that for?

I would absolutely love to see this repurposed as a bookmark when new posts are added to the view. If five posts were just added, there will be a thick line between what I've read and the five new posts. 

You can list this on your FEATURES page. It's THAT awesome.

**Comment by jeena** [comment] 2012-11-12 18:47
The thing you see as a thicker line is just the shadow which is on the zebra list.

Otherwise this is a duplicate of #33 so I will close it but would love you to contribute to try to find out how this feature should work in detail because for now there are some good suggestions but it is still not quite clear how it would be best to work.

**Closed as completed by jeena** 2012-11-12 18:47 UTC
Labels: duplicate
