### ISSUE TITLE
Empty Mentions view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#64] opened 2012-11-18 14:56 UTC
With some entity, Mentions view is empty.
It's OK with https://poweruser.tent.is
It's empty with http://work.to.it (that has link to the same tent.is)

It may not be significant given it appears in both cases, but Console says:

> 18/11/12 15:40:46,017 Tentia[89176]: js<OauthView>: undefined:0: TypeError: 'undefined' is not a function
> 18/11/12 15:41:16,864 Tentia[89176]: jsa<MentionsView>: findProfileURL Not Found (https://davew.tent.is): 

I tried each case more than twice. Between each try I revoked Tentia authorization and cleaned Tentia's stuff in ~/Library/

**Comment by jeena** [comment] 2012-11-18 22:21
I assume the problem is that you used your https://poweruser.tent.is entity but wrote http:// instead of https:// while logging in. Then the browser will redirect from http to https and everything seems working nice but then it queries for the wrong entity (the one without s) and therefor it doesn't find any mentioned statuses.

I changed it now so it uses the entity from the profile, not the one you put in. It will be fixed in the next version, but for now just log in with https://

**Closed as completed** 2012-11-18 22:21 UTC
