### ISSUE TITLE
Mention for ^tent created incorrectly

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#78] opened 2012-11-28 17:59 UTC
In the post represented by the JSON below, Tentia created an incorrect mention for ^tent. 

Is this by design? Meaning that Tentia only includes what the user enters instead of assuming *.tent.is?

``` json
{
  "entity": "https://marco.tent.is",
  "licenses": [

  ],
  "content": {
    "text": "^tjreo.tent.is That's what I'm not sure right now. Maybe ^tent can tell us about it :)"
  },
  "published_at": 1354124788,
  "permissions": {
    "public": true
  },
  "id": "q3tnr7",
  "attachments": [

  ],
  "type": "https://tent.io/types/post/status/v0.1.0",
  "version": 1,
  "app": {
    "url": "http://jabs.nu/Tentia/",
    "name": "Tentia"
  },
  "mentions": [
    {
      "entity": "https://tjreo.tent.is",
      "post": "l3asro"
    },
    {
      "entity": "https://tent"
    }
  ]
}
```

**Comment by jeena** [comment] 2012-11-28 18:02
Yes, exactly, Tentia can't know if when you write ^user you mean https://user.tent.is or http://user.lavv.us or http://campr.me/user or whatever. Actually it should be changed to show a error instead of sending this.

**Comment by tjreo** [comment] 2012-11-28 18:52
I agree that sending the message with an errant mention is not ideal. The best solution in my opinion is to offer suggestions from:
- People already mentioned in the post
- People they follow
- Their followers

**Comment by poweruser82** [comment] 2012-11-28 18:54
Autocompletion would help.

**Comment by jeena** [comment] 2012-11-28 19:15
Ideally like Facebook does it, but that will take some time before I can implement that, btw. it is already a different issue #28

**Comment by jeena** [comment] 2013-02-18 10:18
Duplicate of #138

**Closed as completed by jeena** 2013-02-18 10:18 UTC
Labels: duplicate
