### ISSUE TITLE
Allow me to repost

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#52] opened 2012-11-13 03:34 UTC
I do not see the ability to repost something in Tentia. That's a big deal.

**Comment by jeena** [comment] 2012-11-13 07:36
Yes, sorry this is not implemented yet and will first be implemented after a Linux version is working in some way.

**Comment by jeena** [comment] 2012-11-18 23:27
I now close it because it is a duplicate of #48

**Closed as completed by jeena** 2012-11-18 23:27 UTC
Labels: duplicate
