### ISSUE TITLE
every time i login, auth-page opens twice

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#171] opened 2013-02-20 16:37 UTC

**Comment by jeena** [comment] 2013-02-20 16:44
Linux or OS X?

**Comment by ghost** [comment] 2013-02-20 17:01
in osx, tried with firefox, chrome, safari – every time.

**Comment by poweruser82** [comment] 2013-02-20 17:25
Duplicate of #130 ?

**Comment by ghost** [comment] 2013-02-20 17:30
@poweruser82 yes, most likely a duplicate

opens two pages with different `client_id`s

**Comment by jeena** [comment] 2013-02-21 06:23
Hm ok I tested it now and it only happens for tent.is accounts, not for self hosted. (Btw. far too many of us are on tent.is, that is not like decentralisation works ...)

Like @noformnocontent says it opens two pages with different client_id:s and so if you try to authenticate with the second page bungloo will not let you because of the fraud protection mechanism. So the workaround for now is to close the second tab and authenticate with the first one.

But I need to have a closer look on what is actually happening before I can fix it or tell why exactly this is happening.

**Comment by jeena** [comment] 2013-02-21 21:06
Ok this seems to have been resolved on the tent.is side because it is now working again :)

**Closed as completed by jeena** 2013-02-21 21:06 UTC
Labels: invalid
